services:
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Same2u
    ports:
      - 27017:27017
    volumes:
      - ./database/data:/data/db